# Site settings
title: 异星幻想II
email: kf@lesafe.cn
description: > # this means to ignore newlines until "baseurl:"
  杭州乐赛孚科技有限公司版权所有<br/>
  ©2013-2015. All Rights Reserved.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yxhx2.com" # the base hostname & protocol for your site

host: 0.0.0.0
port: 4000

# Build settings
markdown: kramdown
