# Site settings
title: 异星幻想
email: kf@lesafe.cn
description: > # this means to ignore newlines until "baseurl:"
  BEST 3D MMORPG Since 2013 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yxhx2.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
