# Site settings
title: 异星幻想II
email: kf@lesafe.cn
description: > # this means to ignore newlines until "baseurl:"
  杭州乐赛孚<br/>
  一起玩游戏吧
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yxhx2.com" # the base hostname & protocol for your site

host: 0.0.0.0
port: 4000

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->