# Site settings
title: 异星幻想2官方网站
email: kf@lesafe.cn
description: > # this means to ignore newlines until "baseurl:"
  用心做游戏
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yxhx2.com" # the base hostname & protocol for your site

host: 0.0.0.0
port: 4000

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Download settings
download-url-pc: "http://file.lesafe.cn/yxhx2.1.zip"
download-url-android: "http://file.lesafe.cn/yxhx2.1.000000.60614.apk"
download-url-ios: ""